version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest

    environment:
      CI_IMAGE_NAME: 'whistle/ci'
      PACKER_VERSION: 1.1.0
      TERRAFORM_VERSION: 0.12.6

    steps:
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-

      - checkout
      - run:
          name: checkout-submodules
          command: |
            set -eo pipefail

            git submodule sync
            git submodule update --init

      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - setup_remote_docker:
          version: 17.10.0-ce

      - run:
          name: docker login
          command: |
            set -eo pipefail

            docker info
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      - restore_cache:
          keys:
            - docker-tar-v2-{{ .Branch }}-{{ .Revision }}
            - docker-tar-v2-{{ .Branch }}-
            - docker-tar-v2-

      - run:
          name: Load docker image
          command: |
            set -eo pipefail

            if [[ -e ~/docker/image.tar ]]; then
              docker load --input ~/docker/image.tar
            fi

      - run:
          name: Docker Build
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            cmd=(
              docker build
              --rm=false

              --build-arg "TERRAFORM_VERSION=${TERRAFORM_VERSION}"
              --build-arg "PACKER_VERSION=${PACKER_VERSION}"

              -t "$build_tag"
              .
            )

            "${cmd[@]}"

      - run:
          name: Save build
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            mkdir -pv ~/docker

            # The history is also required to get each individual layer.
            docker save "$build_tag" $(docker history -q "$build_tag") > ~/docker/image.tar

      - save_cache:
          key: docker-tar-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/docker"

      - run:
          name: Execute acceptance test
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            docker run --entrypoint /bin/sh "$build_tag" -c "gem list | grep covalence"
            docker run --entrypoint /bin/sh "$build_tag" -c "aws --version"

            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "packer version"
            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "terraform version"

      - deploy:
          name: Register CI image
          command: |
            set -eo pipefail
            shopt -s nullglob

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            push_tags=()

            case "$CIRCLE_BRANCH" in
              master)
                push_tags+=(
                  "${CI_IMAGE_NAME}:${PACKER_VERSION}.${TERRAFORM_VERSION}.${CIRCLE_BUILD_NUM}"
                  "latest"
                )
                ;;
            esac

            for tag in "${push_tags[@]}"; do
              docker tag "$build_tag" "$tag"
              docker push "$tag"
            done
