version: 2

jobs:
  build:
    docker:
      - image: alpine:3.7
    environment:
      PACKER_VERSION: 1.1.0
      TERRAFORM_VERSION: 0.12.5
      CI_CONTAINER_NAME: 'whistle-ci'
      TF_IMAGE: 'unifio/terraform'
      PKR_IMAGE: 'unifio/packer'
      CI_IMAGE_NAME: 'whistle/ci'
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - setup_remote_docker:
          version: 17.10.0-ce

      - run:
          name: Install dependencies
          command: |
            set -exv

            apk add --no-cache \
              bash \
              curl \
              docker \
              jq

      - run:
          name: docker info
          command: docker info

      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - restore_cache:
          keys:
            - docker-tar-v1-{{ .Branch }}-{{ .Revision }}
            - docker-tar-v1-{{ .Branch }}-
            - docker-tar-v1-

      - run:
          name: Load docker image
          command: |
            set -exv

            if [[ -e ~/docker/image.tar ]]; then
              docker load --input ~/docker/image.tar
            fi

      - run:
          name: Docker Build
          command: |
            set -exv

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            cmd=(
              docker build
              --rm=false

              --build-arg "TERRAFORM_VERSION=${TERRAFORM_VERSION}"
              --build-arg "PACKER_VERSION=${PACKER_VERSION}"

              -t "$build_tag"
              .
            )

            "${cmd[@]}"

      - run:
          name: Save build
          command: |
            set -exv

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            mkdir -pv ~/docker
            docker save "$build_tag" > ~/docker/image.tar

      - save_cache:
          key: docker-tar-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/docker"

      - run:
          name: Execute acceptance test
          command: |
            set -exv

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            docker run --entrypoint /bin/sh "$build_tag" -c "gem list | grep covalence"
            docker run --entrypoint /bin/sh "$build_tag" -c "aws --version"

            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "packer version"
            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "terraform version"

      - deploy:
          name: Register CI image
          command: |
            set -exv

            build_tag="${CI_IMAGE_NAME}:build-${CIRCLE_BUILD_NUM}"

            push_tags=(
              "${CI_IMAGE_NAME}:${PACKER_VERSION}.${TERRAFORM_VERSION}.${CIRCLE_BUILD_NUM}"
            )

            case "$CIRCLE_BRANCH" in
              master)
                for tag in "${push_tags[@]}"; do
                  docker tag "$build_tag" "$tag"

                  docker push "${CI_IMAGE_NAME}":${PACKER_VERSION}.${TERRAFORM_VERSION}.${CIRCLE_BUILD_NUM}
                done
                ;;
            esac

