version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest

    environment:
      CI_IMAGE_NAME: 'whistle/ci'
      PACKER_VERSION: '1.4.4'
      TERRAFORM_VERSION: '0.12.19'
      ALPINE_VERSION: '3.10'
      DUMBINIT_VERSION: '1.2.2'
      GOSU_VERSION: '1.11'
      RUBY_VERSION: '2.5.5'
      SOPS_VERSION: '3.3.1'
      TERRAGRUNT_VERSION: '0.23.24'
      BUNDLER_VERSION: '1.17.3'
    steps:
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-

      - checkout
      - run:
          name: checkout-submodules
          command: |
            set -eo pipefail

            git submodule sync
            git submodule update --init

      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - setup_remote_docker:
          version: 17.10.0-ce

      - run:
          name: docker info
          command: |
            set -eo pipefail

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker info

      - restore_cache:
          keys:
            - docker-tar-v2-{{ .Branch }}-{{ .Revision }}
            - docker-tar-v2-{{ .Branch }}-
            - docker-tar-v2-

      - run:
          name: Load docker image
          command: |
            set -eo pipefail

            if [[ -e ~/docker/image.tar ]]; then
              docker load --input ~/docker/image.tar
            fi

      - run:
          name: Docker Build
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build"
            # DEVOPS-2520 Grab the latest short sha for covalence
            COVALENCE_VERSION=$(wget -qO- https://api.github.com/repos/WhistleLabs/covalence/commits/HEAD | jq -r '.sha' |  cut -b -7)
            build() {
              cmd=(
                docker build
                --rm=false
                --build-arg CI_IMAGE_NAME
                --build-arg PACKER_VERSION
                --build-arg TERRAFORM_VERSION
                --build-arg ALPINE_VERSION
                --build-arg COVALENCE_VERSION=$COVALENCE_VERSION
                --build-arg DUMBINIT_VERSION
                --build-arg GOSU_VERSION
                --build-arg RUBY_VERSION
                --build-arg SOPS_VERSION
                --build-arg TERRAGRUNT_VERSION
                --build-arg BUNDLER_VERSION
              )
              "${cmd[@]}" "$@"
            }

            # This is a multi-stage build, which means we need to cache both stages.
            build -t "$build_tag-build" --target build .
            build -t "$build_tag-covbuild" --target covbuild .
            build -t "$build_tag" .

      - run:
          name: Save build
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build"

            mkdir -pv ~/docker

            get-image-ids() {
              local img
              for img in "$@"; do
                docker history -q "$img" | grep -v '<missing>' | xargs
              done
            }

            # The history is also required to get each individual layer.
            # This is a multi-stage build, which means we need to cache both stages.
            image_ids=($(get-image-ids "$build_tag" "$build_tag-build" "$build_tag-covbuild"))
            docker save "$build_tag" "${image_ids[@]}" > ~/docker/image.tar

      - save_cache:
          key: docker-tar-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/docker"

      - run:
          name: Execute acceptance test
          command: |
            set -eo pipefail

            build_tag="${CI_IMAGE_NAME}:build"
            # DEVOPS-2520 Get latest covalence head sha to verify it matches whats installed
            COVALENCE_VERSION=$(wget -qO- https://api.github.com/repos/WhistleLabs/covalence/commits/HEAD | jq -r '.sha' |  cut -b -7)
            echo "latest covalence sha is: $COVALENCE_VERSION"
            docker run --entrypoint /bin/sh "$build_tag" -c "bundle info covalence"
            docker run --entrypoint /bin/sh "$build_tag" -c "aws --version"

            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "packer version"
            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "terraform version"
            docker run -e CHECKPOINT_DISABLE=1 --entrypoint /bin/sh "${build_tag}" -c "terragrunt --version"
            docker run --entrypoint /bin/sh "$build_tag" -c "lookup --version"

      - deploy:
          name: Register CI image
          command: |
            set -eo pipefail
            shopt -s nullglob

            build_tag="${CI_IMAGE_NAME}:build"

            push_tags=()

            case "$CIRCLE_BRANCH" in
              master)
                push_tags+=(
                  "${CI_IMAGE_NAME}:${PACKER_VERSION}.${TERRAFORM_VERSION}.${CIRCLE_BUILD_NUM}"
                  "${CI_IMAGE_NAME}:latest"
                )
                ;;
            esac

            for tag in "${push_tags[@]}"; do
              docker tag "$build_tag" "$tag"
              docker push "$tag"
            done
